-- <단축키>
-- 커서가 있는 라인 실행: ctrl + enter
-- 여러 문장 한번에 실행: 블록 잡고 -> ALT + X
-- 주석: Ctrl + /

-- 회원 테이블 만들기
CREATE TABLE CUSTOMER (
    ID      INT PRIMARY KEY, -- PK는 유니크와 NOT null 속성을 포함
    NAME    VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100)
);

-- 주문 테이블 만들기
CREATE TABLE ORDERS (
    ORDER_NO    INT PRIMARY KEY COMMENT '주문번호', -- 컬럼에대한 설명
    SALESMAN_ID INT COMMENT '판매자아이디', -- 이름에 여러단어가 있으면 _언더바로 연결
    ORDER_DATE  DATE NOT NULL COMMENT '주문일자'
);

-- Q1. 카테고리 테이블
CREATE TABLE CATEGORIES (
    CATEGORY_ID INT PRIMARY KEY COMMENT '카테고리아이디',
    CATEGORY_NAME VARCHAR(100) NOT NULL COMMENT '카테고리명'
);

-- Q2. 위치
CREATE TABLE LOCATION (
    LOCATION_ID INT PRIMARY KEY,
    ADDRESS     VARCHAR(255) NOT NULL,
    POSTAL_CODE VARCHAR(20),
    CITY        VARCHAR(50)
);

-- Q3. 식단
CREATE TABLE MENUS (
  MENU_ID INT PRIMARY KEY COMMENT '메뉴아이디',
  MENU_NAME CHAR(10) NOT NULL COMMENT '메뉴명',
  KILOCALORIES INT NOT NULL COMMENT '칼로리',
  PRICE INT NOT NULL COMMENT '가격'
);

-- Q4. 강의
CREATE TABLE CURRICULUM(
  NO  INT NOT NULL PRIMARY KEY COMMENT '과목번호',
  NAME VARCHAR(30) COMMENT '과목명',
  POINTS INT COMMENT '학점',
  PROFID INT COMMENT '교수 번호'
  );

-- Q5. 부서
CREATE TABLE DEPT(
	DEPT_NO INT PRIMARY KEY COMMENT '부서번호',
	DEPT_NAME VARCHAR(20) COMMENT '부서명',
	DEPT_LOC VARCHAR(20) COMMENT '부서위치' 
);

-- Q6. 직원
CREATE TABLE EMP(
	EMP_NO INT PRIMARY KEY,
	DEPT_NO INT,
	EMP_NAME VARCHAR(10),
	HDATE DATE
);

-- Q7. 상영관
CREATE TABLE CINEMA (
    THEATER_NO INT PRIMARY KEY COMMENT '상영관번호',
    LOCATION VARCHAR(100)  COMMENT '위치',
    TEL VARCHAR(50)  COMMENT '전화번호'
);

-- Q8. 영화예약
CREATE TABLE RESERVATION (
    MOVIE_NAME VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    SEAT_NO INT,
    DATE DATE,
    PRICE INT
);
