-- update문으로 테이블에서 데이터 변경하기

-- 모든 회원 이름을 도우너로 변경하기
UPDATE CUSTOMER SET NAME = '도우너';

-- 모든 회원의 이름을 둘리, 주소를 서울로 변경하기
UPDATE CUSTOMER 
SET NAME ='둘리', ADDRESS ='서울';

-- 회원번호가 1인 회원의 주소를 제주도로 변경하기
UPDATE CUSTOMER SET ADDRESS = '제주도'
WHERE CUSTOMER_NO = 1;

SELECT * FROM CUSTOMER C 


SELECT * from BOOK B ;

UPDATE BOOK SET PUBLISHER = '믿음사'
WHERE PRICE BETWEEN 10000 AND 30000;

UPDATE BOOK set PUBLISHER = '없음', PRICE = 0
WHERE PUB_DATE is NULL ;

SELECT * FROM CONTACTS C ;

UPDATE CONTACTS SET EMAIL = 'fern@gmail.com'
WHERE FIRST_NAME = '수아';

UPDATE CONTACTS SET FIRST_NAME = '지수'
WHERE LAST_NAME = '이' AND PHONE LIKE ('%2341%');

UPDATE CONTACTS set FIRST_NAME  = '현우', PHONE = '010-1234-5678'
WHERE last_name = '최';


UPDATE CLASS SET CLASS_TIME = '12:30';

SELECT * FROM CLASS C ;

UPDATE CLASS set CLASS_NAME = '문학' WHERE CLASS_NO ='2';

SELECT * FROM PRODUCT P ;

UPDATE PRODUCT SET PRICE = 5000 WHERE PRODUCT_NO IN (1, 3, 5);

UPDATE PRODUCT SET CATEGORY ='기타' WHERE PRODUCT_NO BETWEEN 2 AND 4;


